pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/natsoshko/hillel-qa-auto-python.git'
            }
        }
        stage('Install venv') {
            steps {
                sh '''apt-get update
                    apt-get install -y python3 python3-dev
                    apt install -y python3-pip
                    rm -rf venv
                    apt install -y python3.13-venv
                    python3 -m venv venv'''
            }
        }
        stage('Install requirements') {
            steps {
                sh '''#!/bin/bash
                    source venv/bin/activate
                    pip install -r requirements.txt
                    playwright install --with-deps chromium'''
            }
        }
        stage('Run tests') {
            steps {
                sh '''#!/bin/bash
                    source venv/bin/activate
                    xvfb-run pytest lesson_30/2_variant/tests -v --junitxml=test-results.xml --alluredir=allure-results'''
            }
        }
    }

    post {
        always {
            junit 'test-results.xml'
            allure commandline: 'Allure',
                includeProperties: false,
                jdk: '',
                resultPolicy: 'LEAVE_AS_IS',
                results: [[path: 'allure-results']]
        }
    }
}